find_path(JPEG_INCLUDE_DIR NAMES jinclude.h PATHS ${CONAN_INCLUDE_DIRS_LIBJPEG} NO_CMAKE_FIND_ROOT_PATH)
find_library(JPEG_LIBRARY NAMES ${CONAN_LIBS_LIBJPEG} PATHS ${CONAN_LIB_DIRS_LIBJPEG} NO_CMAKE_FIND_ROOT_PATH)

MESSAGE("** JPEG ALREADY FOUND BY CONAN!")
SET(JPEG_FOUND TRUE)
MESSAGE("** FOUND JPEG:  ${JPEG_LIBRARY}")
MESSAGE("** FOUND JPEG INCLUDE:  ${JPEG_INCLUDE_DIR}")

set(JPEG_INCLUDE_DIRS ${JPEG_INCLUDE_DIR})
set(JPEG_LIBRARIES ${JPEG_LIBRARY})

mark_as_advanced(JPEG_LIBRARY JPEG_INCLUDE_DIR)


set(PNG_MAJOR_VERSION "8")
set(PNG_MINOR_VERSION "3")
set(PNG_PATCH_VERSION "0")